### ISSUE TITLE
back Arrow Icon not working

### ISSUE THREAD

**Issue by YoucefBen47** [take0ffmedia/react-native-bitmovin-player#19]
Hello, when I click the back arrow in the player it kinda freezes the player but does not navigate back to the previous screen. I'm not sure if this issue was solved in the last versions because the app was crashing when I tested the last version.
I hope this back arrow issue would be fixed or if there is a way to disable that back arrow so I can add one from RN.

**Comment by YoucefBen47** [comment]
Perfect ! Thank you so much.

**Comment by jonathanm-tkf** [comment]
You are welcome!!!
