### ISSUE TITLE
Pod install issue on M1 Mac

### ISSUE THREAD

**Issue by YoucefBen47** [take0ffmedia/react-native-bitmovin-player#5]
[!] CocoaPods could not find compatible versions for pod "BitmovinAnalyticsCollector/BitmovinPlayer":
  In Podfile:
    takeoffmedia-react-native-bitmovin-player (from `../node_modules/@takeoffmedia/react-native-bitmovin-player`) was resolved to 0.1.33, which depends on
      BitmovinAnalyticsCollector/BitmovinPlayer (= 1.18.1)

None of your spec sources contain a spec satisfying the dependency: `BitmovinAnalyticsCollector/BitmovinPlayer (= 1.18.1)`.

**Comment by dweinber** [comment]
This is not specific to M1 macs, https://github.com/bitmovin/cocoapod-specs/ doesn't contain older versions of the Bitmovin Analytics (iOS analytics collector releases were only published in https://github.com/bitmovin/bitmovin-analytics-collector-ios previously). 
I'd recommend updating to one of the latest versions of Bitmovin Analytics, i.e. `1.21.0` or `2.1.0`.
